---
- hosts: FreshlyInstalledBoards
  remote_user: muhkuh
  become: yes
  become_user: root
  vars:
    ask_pass: True
    ansible_ssh_pass: muhkuh65536
  vars_prompt:
  - name: cfg_hostname
    prompt: 'Please enter the hostname of the new flash station'
    private: no
    when: cfg_hostname is undefined

  tasks:
  - name: disable unneeded hardware
    lineinfile:
      path: /boot/firmware/usercfg.txt
      state: present
      line: '{{ item }}'
    with_items:
      - 'dtoverlay=disable-wifi'
      - 'dtoverlay=disable-bt'
      - 'hdmi_blanking=2'
      - 'disable_splash=1'
      - 'boot_delay=0'

  - name: blacklist unwanted modules
    kernel_blacklist:
      blacklist_file: /etc/modprobe.d/raspi-blacklist.conf
      name: '{{ item }}'
      state: present
    with_items:
      - 'brcmfmac'
      - 'brcmutil'
      - 'bluetooth'
      - 'btsdio'

  - name: uninstall unwanted packets
    apt:
      name: landscape-common, pastebinit, plymouth, snapd, unattended-upgrades, cloud-init
      state: absent
      purge: yes

  - name: Disable unwanted services.
    systemd:
      name: '{{ item }}'
      enabled: no
      state: stopped
    with_items:
      - 'apt-daily.timer'
      - 'announce_ip.service'
      - 'wpa_supplicant.service'
      - 'accounts-daemon.service'

  - name: limit the journal
    ini_file:
      path: /etc/systemd/journald.conf
      section: Journal
      option: SystemMaxUse
      value: 128M
      create: no

  - name: Install the raspberry-ready-led
    unarchive:
      src: https://github.com/muhkuh-sys/org.muhkuh.tools-raspberry-ready-led/releases/download/v0.0.1/raspberry-ready-led-0.0.1-ubuntu-20.04_arm64.tar.gz
      dest: /opt/
      remote_src: yes
  - name: Install the raspberry-ready-led service file
    copy:
      src: /opt/raspberry-ready-led-0.0.1/systemd/ready_led.service
      dest: /lib/systemd/system/
      remote_src: yes
  - name: Enable the raspberry-ready-led service
    systemd:
      name: ready_led.service
      enabled: yes
      masked: no

  - name: set the new hostname
    hostname:
      name: "{{ cfg_hostname }}"

  - name: Install the UDEV rules.
    copy:
      src: data/etc/udev/rules.d/
      dest: /etc/udev/rules.d/
      owner: root
      group: root
      mode: '0644'

  - name: Install the WebUI.
    unarchive:
      src: https://github.com/muhkuh-sys/org.muhkuh.tools-webui/releases/download/v0.0.1/webui-0.0.1-ubuntu-20.04_arm64.tar.gz
      dest: /opt/
      remote_src: yes
  - name: Install the WebUI service file
    copy:
      src: /opt/webui-0.0.1/systemd/muhkuh_webui.service
      dest: /lib/systemd/system/
      remote_src: yes
  - name: Enable the WebUI service
    systemd:
      name: muhkuh_webui.service
      enabled: yes
      masked: no
